version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - moodledata:/var/moodledata

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
    driver: local
  db_data:
    driver: local
