version: '3.1'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    volumes:
      - ./moodle:/var/www/html/
      - ./moodledata:/var/moodledata

  db:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
    driver: local
  db_data: